src/en/contributing/tests.md

It makes sense to use the same setup locally and in CI, plus the current script is broken on Lemmy's `move_views_to_diesel` branch. However, this new script is not merged into main for Lemmy yet, so we need to wait with merging this. 
After merging, lets delete `docker/federation/run-tests.bash` from the Lemmy repo.

Run federation tests natively

---

.drone.yml

Lets do the CI directly in this repo, so it doesnt have to run for every single commit in the Lemmy repo. We should remove it there after merging this PR.

Add drone ci

---

src/en/contributing/websocket_http_api.md

Without it the server returns an error: `invalid type: null, expected struct ListCategories at line 1 column 4`

Add data field in websocket example

---

src/en/federation/administration.md

Documentation for https://github.com/LemmyNet/lemmy/pull/1581. Might be best to wait with merging this, until the code is released in a new version.

Update docs for federation modes

---

src/en/administration/configuration.md
src/en/administration/federation_getting_started.md
src/en/contributing/federation_development.md

Somehow federation instructions, and the allowlist descriptions got removed in the last reworking of being a server admin. This adds instructions for federation.

Add federation instructions.

---

src/en/administration/from_scratch.md

Lemmy is running fine on a fresh test server at https://lemmytest.nutomic.com with these instructions. However, image uploads are failing with "Couln't upload file, No such file or directory (os error 2)". Any idea what that could be? The data path exists and dependencies are installed.
Todo:
I also think that we could remove the disclaimer at the top, because there is not much that can go wrong with these instructions imo. Whats more important is that we emphasize mentioning the installation method in our issue templates.

Rewrite instructions for manually installation

---

src/en/administration/administration.md

Lemmy is also listed in their [application catalog](https://yunohost.org/en/apps), but its not possible to link to a specific item there, and the documentation link is broken.

Add yunohost installation method

---

.drone.yml

To fix CI error: "package `handlebars v4.3.0` cannot be built because it requires rustc 1.57 or newer, while the currently active rustc version is 1.56.1"

Upgrade Rust to 1.61.0

---

src/en/administration/administration.md
src/en/administration/from_scratch.md

We as developers shouldnt be the first to provide support, because there is already a large enough community who can help with most problems. 
Also see https://github.com/LemmyNet/lemmy/pull/2638

Point out that Github should not be used for support

---

src/en/administration/from_scratch.md
src/en/contributing/local_development.md

Would be good if someone who uses native install could test this once the release candidate is on crates.io. 
I also changed the dependencies as some of them arent needed anymore.

Update from scratch instructions to use embedded pictrs

---

src/en/administration/install_docker.md

The current install instructions are referencing the wrong version.

Fixing v0.17 install instructions.

---

src/es/SUMMARY.md

It's a small typo. [*Guía*](https://es.wiktionary.org/wiki/gu%C3%ADa) is the correct spelling.

Correct typo from Spanish translation

---

src/en/administration/install_docker.md

This is a confusing thing for people setting up a new server exposed through another layer of proxy, so documenting it explicitly will hopefully help save people some time.

Document Host header proxy gotcha

---

src/en/introduction.md

was previously linking to [this pr](https://github.com/LemmyNet/lemmy-docs/pull/172) for some reason.

fix link to lemmy docs

---

.woodpecker.yml
src/en/introduction.md

Per https://github.com/LemmyNet/lemmy-docs/pull/191#issuecomment-1582497270
Using: https://github.com/crate-ci/typos
You can see this works by looking at [this](https://woodpecker.join-lemmy.org/LemmyNet/lemmy-docs/pipeline/89/1) run where there is an intentional typo.
I wanted to install the latest version of typos but there is a weird problem that even when I set the docker image to the latest version of rust it was still using an old version that didn't work for typos.
@Nutomic recommended using a prebuilt binary for now so that's what I did.
An alternative would be to use https://hub.docker.com/r/imunew/typos-cli but who knows if it will be maintained. 
Open to suggestions for improving this.

check for typos in ci

---

src/en/administration/from_scratch.md

This is a minor PR adding some caveats about Lemmy setups:
* The fact that Lemmy-ui does not currently handle a lack of pict-rs gracefully
* The fact that SSL connections to the database are not supported
Hopefully these notes will save future admins some time with debugging!

Add caveats regarding pict-rs and ssl connections to database

---

src/en/administration/install_docker.md

The current `nginx.conf` in the english docker install doc has a very strict `http_accept` header check. It prevents other services in the Fediverse like Mastodon and Kbin federating with the Lemmy instance due to the way they send the `http_accept` header.
The change updates the `http_accept` header check and aligns it with the one in the [ansible template](https://github.com/LemmyNet/lemmy-ansible/blob/fa12b2e0705a70ebaa2dde19043ee9ae38e4c74c/templates/nginx.conf#L63).

Fix http_accept header in nginx.conf for docker install

---

src/en/administration/first_steps.md

In https://github.com/LemmyNet/joinlemmy-site/commit/acd202c5909fe85e6c4c31ce2510c3635d99ee0c, the requirements for an instance being visible on join-lemmy.org changed. This PR updates the docs to reflect the new requirements.

Add new requirements for an instance being included on join-lemmy.org

---

src/en/SUMMARY.md
src/en/administration/tor_hidden_service.md

This PR intends to implement issue https://github.com/LemmyNet/lemmy-docs/issues/187 . The only thing I'm iffy on right now is how to hook this up to the main documentation. Configuring Tor and running an onion site probably isn't everybody's cup of tea.
A second pair of eyes on this wouldn't hurt either. For some reason I wasn't able to proxy the `.onion` address to `http://lemmy`. I suspect it was related to SSL, because it isn't supported on the Tor network (last I remember anyway, I could be wrong).
- Which page/section should link to `tor_hidden_service.md`?
- How should it be mentioned in the documentation? i.e., "If you want to proxy Lemmy through Tor click _here_."
- Can someone validate what I've done here? I didn't see anything out of the ordinary security-wise in my initial …

Add tor_hidden_service.md

---

src/en/contributors/02-local-development.md

The contributor docs just had a small typo for running the federation test script.

Small correction for running the API tests

---

src/en/contributors/02-local-development.md

Fixes the package names on Arch Linux.
```shell
ldd ./target/debug/lemmy_server                                                                                                                                                                                                        
libssl.so.3 => /usr/lib/libssl.so.3 (0x00007f4435d60000)
libpq.so.5 => /usr/lib/libpq.so.5 (0x00007f4435d0d000)
```
Checking which packages own the relevant files:
```shell
pacman -Qo /usr/lib/libssl.so.3
/usr/lib/libssl.so.3 is owned by openssl 3.1.1-1
pacman -Qo /usr/include/openssl/
/usr/include/openssl/ is owned by openssl 3.1.1-1
```
```shell
pacman -Qo /usr/lib/libpq.so.5
/usr/lib/libpq.so.5 is owned by postgresql-libs 15.3-1
pacman -Qo /usr/include/postgresql/
/usr/include/postgresql/ is owned by …
```

Correct package names for Arch local development

---

src/administration/from_scratch.md

Tiny thing that I just noticed when browsing the docs:
Updated the link to the docker-compose file and its line to refer to the actual line with the pictrs version in it.

Update line in link to docker-compose

---

src/administration/from_scratch.md

Updated out of date LEMMY_UI environment variables, and added caution with failing postgresql configuration

Update from_scratch.md (LEMMY_UI variables, and added note about failing postgresql config)

---

src/contributors/02-local-development.md

Homebrew changed their default installation location, so using `/usr/local` might not work out-of-the-box for everyone, and will not work for more and more people going forward.

Replace brew prefix with dynamic lookup

---

src/administration/install_docker.md

I struggled a bit on this when setting up my docker install because there was no instruction to download this file. I just had to search the repository the other files were being downloaded from to find it.

Add nginx default config to the list of default config files to download in the docker install instructions

---

src/administration/first_steps.md

Updated references to the old matrix channel to be to https://matrix.to/#/#lemmy-admin-support-topics:discuss.online instead.
I've updated the Matrix link to use the new Space to help people find the correct support.
Relates to:
https://github.com/LemmyNet/lemmy/pull/3599
https://github.com/LemmyNet/joinlemmy-site/pull/220

Updated Lemmy Matrix Support link

---

src/administration/from_scratch.md

Some of the notes scattered about on Lenny discussions and issues into from-scratch install. This still needs testing on a virgin Ubuntu 22.04 install to make sure it has all the libraries and no steps are missing.
Example checkouts are now 0.18.0 version of Lemmy. Ubuntu 22.04 is mentioned along with Ubuntu 20.04

From scratch updates2023 06 30

---

src/administration/tor_hidden_service.md

Fixes prompted by comments in #190 
* Hidden service forwards 10080 to 80
* Compose forwards proxy:10080 to 127.0.0.1:10080
* Remove strict transport transport security

tor_hidden_service: Fix port forwarding

---

src/administration/install_docker.md

This commit updates the TLS guide from Ubuntu 20.04 to 22.04 (latest LTS).

Updated link to latest Ubuntu

---

src/contributors/04-api.md

The content in the README was apparently moved in https://github.com/LemmyNet/lemmy/commit/050216eed97380c8c1682ba065cf5e62f0961934

Fix libraries link in API documentation

---

.woodpecker.yml

It was removed in 0dc13b4ea11daaa07d964c17f7a622e3a222367a and since then the CI build throws a bunch of errors but still exits with status code 0.
There's an [open issue in mdBook](https://github.com/rust-lang/mdBook/issues/1094) regarding the behavior of broken links and the exit code but it looks stale.

Restore update-includes.sh script in CI

---

src/contributors/01-overview.md

It is currently linking to the overall group repo instead of the one specifically for the `js-client`

Fix linking to wrong page for 'lemmy-js-client' on contributers docs

---

src/administration/install_docker.md

In https://github.com/LemmyNet/lemmy-ansible/pull/161 the `proxy_params` file was introduced. This file needs to be downloaded so it gets mounted in the `nginx` container.
https://github.com/LemmyNet/lemmy-ansible/pull/161/files#diff-a78c3c6b9adf66d21f26347f9c0cdb09ed9813c8cd95e56bea726bc86068c294

Add `proxy_params` to list of files to download for docker-compose

---

src/administration/horizontal_scaling.md
src/administration/troubleshooting.md

For https://github.com/LemmyNet/lemmy/pull/3605

Add info about horizontal scaling and debugging persistent queue

---

src/administration/backup_and_restore.md
src/administration/install_docker.md
src/administration/troubleshooting.md

Docker Compose v2 was released in 2020. v1 was deprecated in 2022 and no longer receives any updates as of July 2023. v2 uses `docker compose` rather than `docker-compose`.

Remove references to legacy Docker Compose v1

---

src/contributors/04-api.md

On the [API page](https://join-lemmy.org/docs/contributors/04-api.html), the link to the current API version currently points to a file that no longer exists: \
https://github.com/LemmyNet/lemmy-js-client/blob/main/src/types/others.ts#L1
This pull request updates the link to point to the correct file: \
https://github.com/LemmyNet/lemmy-js-client/blob/main/src/other_types.ts#L1

Update link to current API version

---

src/administration/prometheus.md

Prometheus is included in the default build as of commit https://github.com/LemmyNet/lemmy/commit/45bed71c368fe3c72a182025505d6e1ca49bfdd9#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542 and PR https://github.com/LemmyNet/lemmy/pull/4071

Clarify that prometheus is included by default

---

src/administration/from_scratch.md

We need to have `cc` command for this step:
```
cargo build --release --features embed-pictrs
```
So installing `gcc` early on will help with that.

Add gcc to from_scratch.md instructions

---

src/contributors/08-plugins.md

I meant to leave https://github.com/LemmyNet/lemmy-docs/pull/306 as draft, but instead Im adding some introduction/clarification this way.

Add introduction for plugins

---

src/administration/horizontal_scaling.md

As requested here: https://github.com/LemmyNet/lemmy/issues/4603#issuecomment-2124696752

Update horizontal_scaling.md with ENV parameters

---

src/administration/troubleshooting.md

When troubleshooting, `verbose` value for `RUST_LOG` doesn't print anything, not even `info` values. So if you're trying to figure out why your upgrade isn't loading in the UI, you turn on verbose logging but can't see that the DB migrations are running.
Updated the "most verbose" line in the Troubleshooting doc to use `debug` instead, which provides more context than `info`.

Update RUST_LOG from verbose to debug, as verbose outputs no logging

---

src/contributors/02-local-development.md

I tested this one, and it works for `cargo build`

Adding ~/.cargo/config.toml local dev instructions.

---

src/administration/theming.md

Reference to issue #251. Updated the Bootstrap version number (v4) to the latest version (v5).

Replaced references of Bootstrap version v4 with v5 in the Theming Guide

---

src/administration/from_scratch.md

Not supported anymore in 1.0, see https://github.com/LemmyNet/lemmy/pull/5023

Remove embedded pictrs in from scratch instructions (fixes #219)

---

src/administration/configuration.md

Maybe we should change the default config path in Lemmy from `config/config.hjson` to `config/lemmy.hjson` to be more consistent with the docker install?

Update config docs (fixes #6)

---

assets/separate_subdomains/nginx/nginx_internal.conf
assets/separate_subdomains/traefik/compose.yml
src/SUMMARY.md
src/administration/separate_subdomains.md

As discussed in the [Lemmy Matrix chat](https://matrix.to/#/#lemmy-support-general:discuss.online), this PR adds documentation for running the Lemmy backend and frontend on separate subdomains.
The Traefik configuration has been tested, however I am unable to test the NGINX configuration. If possible, it would be great if someone could test it.
- This PR references a third-party Docker container (for the UI) which is required for this configuration.
Please let me know if there are any issues! I'm always hoping for constructive feedback.

Add documentation for running Lemmy on separate subdomains

---

src/contributors/02-local-development.md

Reference: #370
Added installation steps for [taplo](https://taplo.tamasfe.dev/) and [pgformatter](https://github.com/darold/pgformatter).
The second one has very convoluted installation guide on its github page, so I added 3 separate commands for different packet managers. Tested only on ubuntu, but found that the package name is the same on [arch](https://archlinux.org/packages/extra/any/pgformatter/) and [mac](https://formulae.brew.sh/formula/pgformatter).
Decided to put them to a separate section, since these tools are not essential for contribution.

Added documentation for code formatting tools (ref #370)

---

src/administration/install_docker.md

there isn't {{lemmy_port}} in the latest default config files

Update install_docker.md - remove {{lemmy_port}}

---

assets/docker-compose.yml

Currently, the `LEMMY_UI_LEMMY_EXTERNAL_HOST` is hardcoded to lemmy.ml. Updating to be a var substitution to `{{ domain }}` like how the docs mention.
Problem originally found at: https://ponder.cat/post/3716662

Substitute LEMMY_UI_LEMMY_EXTERNAL_HOST in Compose
