LemmyNet/lemmy-docs

book.toml

Strings for Russian language was added.

Russian language

---

src/en/SUMMARY.md
src/en/administration/first_steps.md

Explain what new admins should do after setting up their instance #90

Administration First Steps

---

src/en/administration/from_scratch.md

as per the conversation in the [lemmy matrix channel]( https://matrix.to/#/!BZVTUuEiNmRcbFeLeI:matrix.org/$1639845665473064Aafrc:matrix.org).
I'm working on a larger rewrite of the documentation based on compiling and running on Debian.

add information on --locked flag

---

src/en/federation/lemmy_protocol.md

See https://github.com/LemmyNet/joinlemmy-site/issues/71

Fix broken link

---

src/en/about/about.md

This will add a notice that the document has many language translated.

Language Change

---

src/en/federation/lemmy_protocol.md
src/id/federation/lemmy_protocol.md

These were still pointing at old file paths.

Fix includes in lemmy protocol document

---

.drone.yml

@dessalines CI failed in #147, please check it this time before merging.

Add curl to CI

---

src/en/administration/install_docker.md

https://github.com/LemmyNet/lemmy/issues/2571

Fix the wrong docker-compose and lemmy.hjson

---

src/en/SUMMARY.md
src/en/administration/administration.md
src/en/administration/caddy.md

adding Caddy configuration example.

adding caddy configuration example

---

src/en/federation/lemmy_protocol.md

Just making sure spelling is consistent as far as I can tell.

remove_data -> removeData

---

src/en/administration/install_docker.md

Updates the docs to fix the docker-compose setup. It is accompnanied by a change in the Lemmy repo to update the docker-compose.yml file.
See: https://github.com/LemmyNet/lemmy/pull/2908

Update docs to fix nginx proxy config for Docker installs

---

src/en/users/03-votes-and-ranking.md

I propose removing this broken link. Unless someone knows what "this page" once linked to.
In which case let me and I'll fix the link.

remove broken link

---

src/en/administration/configuration.md

Relates to this issue https://github.com/LemmyNet/lemmy-docs/issues/207

Removed outdated line from configuration.md

---

src/administration/install_docker.md

I manually tested these on a fresh server, and they work.

Updating docker install docs.

---

src/administration/backup_and_restore.md

This is a full backup, not an incremental.

Fix wording on backup and restore page

---

src/SUMMARY.md
src/administration/prometheus.md

Document the new Prometheus endpoint and how to use it.
Requested as part of this pull request: https://github.com/LemmyNet/lemmy/pull/3456

Prometheus documentation

---

src/SUMMARY.md
src/administration/administration.md
src/administration/horizontal_scaling.md

A collection of notes that will hopefully be useful to any other admins attempting to scale horizontally

Add notes about horizontal scaling

---

src/users/03-votes-and-ranking.md

Problem: There was only an implicit hint that "New Comments" also sorts posts with zero comments to the top.
Solution: Make that behaviour description explicit.

Update 03-votes-and-ranking.md: Clarified wording

---

src/contributors/07-ranking-algo.md
src/users/03-votes-and-ranking.md

Lemmy PR: https://github.com/LemmyNet/lemmy/pull/3907

Adding documentation for scaled rank.

---

src/code_of_conduct.md

This has just been a source of spam anyway.

Remove contact email.

---

src/contributors/02-local-development.md

The lint script has changed to `lint.sh`

Update linter path

---

src/administration/from_scratch.md

- PostgreSQL 16 installation
- Pict-rs specific instructions (folders, ImageMagick AppImage problems in LXC containers, etc.
- Update Lemmy version to 0.18.5 in the docs
- Use /opt/lemmy for deployment (the Linux way (c))
- Update Nodejs and Yarn installation instructions per current updates from Nodesource
- Bump Nodejs version to 20
- Updated Nginx config file

Updated "Install from Scratch" guide

---

src/contributors/07-ranking-algo.md

Adding "voting" as something that determines active.

Adding voting as active.

---

src/users/02-media.md

- These instructions can then be linked to in UIs, where the post_url is a torrent magnet link.
- Context: https://github.com/LemmyNet/lemmy/issues/4204

Add instructions for Torrent-Streaming to docs.

---

src/administration/troubleshooting.md
src/contributors/03-docker-development.md

This is my attempt to improve the documentation on the docker and performance troubleshooting after the 2 days I spent diagnosing such issues.

doc: improve docker and performance troubleshooting

---

src/contributors/02-local-development.md

- Context: https://github.com/LemmyNet/lemmy/pull/4976

Remove openssl from docs.

---

src/administration/administration.md
src/administration/backup_and_restore.md
src/administration/caddy.md
src/administration/federation_getting_started.md
src/administration/first_steps.md
src/administration/from_scratch.md
src/administration/horizontal_scaling.md
src/administration/install_ansible.md
src/administration/install_docker.md
src/administration/on_aws.md
src/administration/prometheus.md
src/administration/tor_hidden_service.md
src/contributors/01-overview.md
src/contributors/02-local-development.md
src/contributors/03-docker-development.md
src/contributors/04-api.md
src/contributors/05-federation.md
src/contributors/06-resources.md
src/contributors/07-ranking-algo.md
src/introduction.md
src/users/01-getting-started.md
src/users/02-media.md
src/users/03-votes-and-ranking.md
src/users/05-censorship-resistance.md
src/users/06-other-features.md
src/users/07-history-of-lemmy.md

Each file should start with h1 (#) and title should match the one in SUMMARY.md

Make file headings consistent

---

src/administration/install_docker.md

Add nginx_resolver replacement note.

---

src/administration/troubleshooting.md

Add nginx caching as possible solution for slow lemmy-ui

---

src/contributors/04-api.md

Going to merge this, I'll have a video showing it shortly.

Changing to not available.

---

src/administration/from_scratch.md

it was removed in https://github.com/LemmyNet/lemmy/pull/4584

Remove version.rs from scratch installation

---

src/contributors/02-local-development.md

Requires https://github.com/LemmyNet/lemmy/pull/5908

Add instructions for changing the database schema
